# github/node.yml
name: Node.js CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      - name: Install dependencies
        run: npm ci

  lint:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v3
      - name: Run linter
        run: npm run lint || echo "No linter configured"

  test:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: npm test || echo "No tests configured"

  build:
    runs-on: ubuntu-latest
    needs: [install, lint, test]
    steps:
      - uses: actions/checkout@v3
      - name: Build project
        run: npm run build || echo "No build script configured"
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: node-build
          path: dist/
